phrase:
  access_token: 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
  project_id: 89209c851abf4b64b9b17aeefbaaf9d5
  push:
    sources:
    - file: ./<locale_name>/.json
      params:
        file_format: simple_json
  pull:
    targets:
    - file: ./<locale_name>/.json
      params:
        file_format: simple_json
