phrase:
  access_token: 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
  project_id: e34195000f8d6ce264d7200050b14086
  push:
    sources:
    - file: ./<locale_name>/.json
      params:
        file_format: simple_json
  pull:
    targets:
    - file: ./<locale_name>/.json
      params:
        file_format: simple_json
